blog/urls.py
from django.urls import path
from . import views
app_name = "blog"


urlpatterns = [
    path('', views.Home  , name = "index" ),
    # path('posts/', views.Post_list , name = "Post_list"),
    path('posts/', views.PostListview.as_view() , name = "Post_list"),
    path('posts/<int:id>/', views.Post_detail , name = "Post_detail"),
    path('posts/<post_id>/comment', views.post_comments , name = "post_comments"),
    # path('posts/<pk>', views.PostDitailview.as_view() , name = "Post_detail"),
    path('ticket/', views.create_ticket , name = "create_ticket"),
    # path('posts/create/', views.crete_post , name = "crete_post"),
    path('posts/create/', views.crete_blog , name = "crete_blog"),
    path('posts/search/', views.post_search , name = "post_search"),
    path('profile/', views.profile , name = "profile"),
    path('profile/delete_post/<post_id>', views.delete_post , name = "delete_post"),
    path('profile/delete_image/<post_id>', views.delete_image , name = "delete_image"),
    path('profile/edit_post/<post_id>', views.edit_post , name = "edit_post"),

 


]

sabzweblog/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static 
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

urlpatterns+=static(settings.MEDIA_URL , document_root =settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django_jalali.db import models as jmodels
from django.urls import reverse
from django_resized import ResizedImageField
from django.db.models.signals import pre_delete
from django.dispatch import receiver
import os
from datetime import datetime
from django.template.defaultfilters import slugify
# Create your models here.
class publishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status = Post.Status.PUBLISH)
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF' ,'Draft'
        PUBLISH = 'PB' , 'Publish'
        REJECTED = 'RJ' , 'Rejected'
        
    author = models.ForeignKey(User , on_delete = models.CASCADE,related_name = "user_posts" ,verbose_name = "نویسنده")
    title = models.CharField(max_length =100 ,verbose_name = "عنوان" )
    description = models.TextField(verbose_name = "توضیحات")
    slug = models.SlugField(max_length =100)
    # time 
    publish = jmodels.jDateTimeField(default=timezone.now,verbose_name = "تاریخ انتشار")
    created = jmodels.jDateTimeField(auto_now_add=True,verbose_name = "تاریخ ساخت")
    updated = jmodels.jDateTimeField(auto_now=True)
    status = models.CharField(max_length =10 , choices = Status.choices , default = Status.DRAFT,verbose_name = "وضعیت")
    reading_time = models.PositiveIntegerField(verbose_name = "تایم مطالعه")
    # objects = models.Manager()
    objects = jmodels.jManager()
    published = publishedManager()
    class Meta:
        ordering = ['-publish']
        # for search index in table 
        indexes = [
            models.Index(fields=['-publish'])
        ]
        verbose_name = "پست"
        verbose_name_plural = "پست ها"
        
        
    def __str__(self) :
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:Post_detail", kwargs={"id": self.id})

    def save(self , *args , **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args,**kwargs)

    def delete(self , *args , **kwargs):
        for img in self.images.all():
            storage , path = img.Image_file.storage , img.Image_file.path
            storage.delete(path)
        super().delete(*args,**kwargs)


class Ticket(models.Model):
    name = models.CharField(max_length =50  ,verbose_name = "نام فرستند")
    massege = models.TextField(verbose_name = "پیام")
    email = models.EmailField(verbose_name = "ایمیل")
    phone = models.CharField(max_length =11 , verbose_name = "تلفن همراه" )
    sunject = models.CharField(max_length =100  , verbose_name = "موضوع پیام")
    class Meta:
        verbose_name = "تیکت"
        verbose_name_plural = "تیکت ها"
        
        
    def __str__(self) :
        return self.name
    
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete = models.CASCADE,related_name = "comments" ,verbose_name = "پست")
    name = models.CharField(max_length =50,verbose_name = "نام")
    body = models.TextField(verbose_name = "متن کامنت")
    created = jmodels.jDateTimeField(auto_now_add=True,verbose_name = "تاریخ ساخت")
    updated = jmodels.jDateTimeField(auto_now=True ,verbose_name = "تاریخ ویرایش")
    active = models.BooleanField(default=False ,verbose_name = "وضعیت")
    class Meta:
        ordering = ['created']
        # for search index in table 
        indexes = [
            models.Index(fields=['created'])
        ]
        verbose_name = "کامنت"
        verbose_name_plural = "کامنت ها"
        
        
    def __str__(self) :
        return f"{self.name} : {self.post}"
    
    
def upload_to(instance, filename):
    # دریافت تاریخ و زمان فعلی
    now = datetime.now()
    # تعیین مسیر آپلود بر اساس سال
    upload_path = os.path.join('Post_image', str(now.year))
    # تعیین نام فایل
    _, ext = os.path.splitext(filename)
    file_name = f'{instance.pk}{ext}'
    # ترکیب مسیر آپلود و نام فایل
    return os.path.join(upload_path, file_name)
class ImagePost(models.Model):
     post = models.ForeignKey(Post,on_delete = models.CASCADE,related_name = "images" ,verbose_name = "پست")
     Image_file = ResizedImageField(upload_to=upload_to , crop=['middle', 'center'] , size=[500,500],quality=75)
     title = models.CharField(max_length =50 , null=True,blank=True , verbose_name = "عنوان")
     description = models.CharField(max_length =255,null=True,blank=True , verbose_name = "توضیحات")
     created = jmodels.jDateTimeField(auto_now_add=True)
     
     class Meta:
        ordering = ['created']
        # for search index in table 
        indexes = [
            models.Index(fields=['created'])
        ]
        verbose_name = "تصویر پست"
        verbose_name_plural = "تصویر پست ها"       
     def __str__(self) :
        return self.title if self.title else self.Image_file.name
    
    
@receiver(pre_delete, sender=ImagePost)
def delete_image_file(sender, instance, **kwargs):
    # بدست آوردن مسیر فایل
    image_path = instance.Image_file.path
    
    # حذف فایل
    if os.path.isfile(image_path):
        os.remove(image_path)

blog/forms.py
from django import forms
from .models import Comment , Post
from django.contrib.auth.models import User

class TicketForm(forms.Form):
     subject_select = (
         ("پیشنهاد" , "پیشنهاد"),
         ("انتقاد" , "انتقاد"),
         ("گزارش" , "گزارش")
     )
     name = forms.CharField(max_length =50 , required=True)
     massege = forms.CharField(widget = forms.Textarea , required=True)
     email = forms.EmailField()
     phone = forms.CharField(max_length =11   , required=True)
     sunject = forms.ChoiceField(choices=subject_select)
    
    
     def clean_phone(self):
         data = self.cleaned_data["phone"]
         if data:
              if not data.isnumeric:
                   raise forms.ValidationError("شماره تلفن اشتباه وارد شده است باید عدد باشد !")
              else:
                   return data
class CommentForm(forms.ModelForm):      
     def clean_name(self):
         name = self.cleaned_data["name"]
         if name :
              if len(name)<3:
                   raise forms.ValidationError("نام کوتاه است!")
              else:
                   return name
     class Meta:
          model = Comment
          # exclude = ['created']
          fields = ['name','body']
class PostForm(forms.Form):
    author = forms.ModelChoiceField(queryset=User.objects.all() ,required=True)
    title = forms.CharField(max_length =50 , required=True)
    description = forms.CharField(widget = forms.Textarea , required=True)
    slug = forms.SlugField(max_length =50 , required=True)
    status_choices = (
        ('DF', 'Draft'),
        ('PB', 'Publish'),
        ('RJ', 'Rejected')
     )
    status = forms.ChoiceField(choices = status_choices ,required=True)    
    reading_time = forms.IntegerField(required=True)

    def clean_title(self):
         title = self.cleaned_data["title"]
         if title:
              if len(title)<3:
                   raise forms.ValidationError("نام کوتاه است!")
              else:
                    return title
               
class CratePost(forms.ModelForm):
     image1 = forms.ImageField(label='تصویر اول')
     image2 = forms.ImageField(label='تصویر دوم')
     class Meta:
          model = Post
          fields = ['title','description','reading_time',]
class SearchForm(forms.Form):
     query = forms.CharField()

blog/views.py
from django.shortcuts import render , get_object_or_404 ,redirect
from django.http import HttpResponse , Http404 
from .models import Post , Ticket , ImagePost
from .forms import *
from django.views.decorators.http import require_POST , require_GET
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic import ListView , DetailView
from django.db.models import Q
from django.contrib.postgres.search import SearchVector , SearchQuery , SearchRank ,TrigramSimilarity
from itertools import chain
# Create your views here.
def Home(request):
    return render(request , "blog/index.html" )

class PostListview(ListView):
    paginate_by = 3  
    queryset = Post.published.all()
    context_object_name = "posts"
    template_name = "blog/list.html"

def Post_detail(request , id):
    post =  get_object_or_404(Post , id=id , status = Post.Status.PUBLISH)
    # try:
    #     post = Post.published.get(id=id)
    # except:
    #     raise Http404("not found post!...")
    form = CommentForm()
    comment = post.comments.filter(active =True)
    context = {
        "post" : post,
        "form" : form,
        "commetn":comment,
    }
    return render (request , "blog/detail.html" , context)
    
def create_ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(
                name = cd["name"],
                massege = cd["massege"],
                email = cd["email"],
                phone = cd["phone"],
                sunject = cd["sunject"],
                )
            return redirect("blog:index")
            
    else:
        form = TicketForm()
        # context = {
        #     "form" : form
        # }
    return render(request, "forms/ticket.html", {"form" : form})    

@require_POST
def post_comments(request , post_id):
    post = get_object_or_404(Post , id=post_id , status = Post.Status.PUBLISH) 
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        "post": post,
        "form" : form,
        "comment":comment
    }
    return render(request , "forms/comment.html" ,context) 

def crete_blog(request):
    if request.method == "POST":
        form = CratePost(request.POST , request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            img1 = ImagePost.objects.create(Image_file=form.cleaned_data['image1'] , post=post)
            post.images.add(img1)
            img2 = ImagePost.objects.create(Image_file=form.cleaned_data['image2'] , post=post)
            post.images.add(img2)
            post.save()
            return redirect("blog:index")
    else:
        form = CratePost()
    return render (request , "blog/createpost.html" , {"form" :form,})

@require_GET
def post_search(request):
    query=None
    result=[]
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # ============
            post_results = Post.objects.filter(
                Q(title__icontains=query) | Q(description__icontains=query)
            )
            image_post_results = ImagePost.objects.filter(
                Q(title__icontains=query) | Q(description__icontains=query)
            )

            result = list(chain(post_results, image_post_results))
            # ==========
            # result = Post.objects.filter(description__search = query)
            # ===================
            # search_query = SearchQuery(query)
            # search_vector = SearchVector('title' , 'description')
            # result = Post.objects.annotate(search=search_vector , rank=SearchRank(search_vector,search_query)).filter(search  = search_query).order_by('-rank')
            #  SearchQuery(query) فارسی کامل پشتیبانی نمیشود
            # ====================
            # post_results = Post.objects.annotate(similarity=TrigramSimilarity('title', query) + TrigramSimilarity('description', query)).filter(similarity__gt=0.1).order_by('-similarity')
            # image_post_results = ImagePost.objects.annotate(similarity=TrigramSimilarity('title', query) + TrigramSimilarity('description', query)).filter(similarity__gt=0.1).order_by('-similarity')
            # result = list(chain(post_results, image_post_results))
    context = {
        'query':query,
        'result':result,
    }
    return render(request , 'blog/index.html' , context)

def profile(request):
    user = request.user
    post = Post.published.filter(author=user)
    # print(post)
    context = {
        'post':post,
    }
    return render(request , 'blog/profile.html' , context)


def delete_post(request, post_id):
    post = get_object_or_404(Post,id=post_id)
    if request.method == "POST":
        post.delete()
        return redirect("blog:profile")
    return render(request, 'forms/delete-post.html' , {post:'post'})

def delete_image(request, post_id):
    image = get_object_or_404(ImagePost,id=post_id)
    image.delete()
    return redirect("blog:profile")
    return render(request, 'forms/delete-image.html' , {image:'image'})
    
def edit_post(request, post_id):
    post = get_object_or_404(Post,id=post_id)
    if request.method == "POST":
            form = CratePost(request.POST , request.FILES , instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.save()
                img1 = ImagePost.objects.create(Image_file=form.cleaned_data['image1'] , post=post)
                post.images.add(img1)
                img2 = ImagePost.objects.create(Image_file=form.cleaned_data['image2'] , post=post)
                post.images.add(img2)
                post.save()
                return redirect("blog:index")
    else:
        form = CratePost( instance=post)
        return render (request , "blog/createpost.html" , {"form" :form, "post" :post})

blog/templates/partials/footer.html
{% comment %} <p>foooter</p> {% endcomment %}

blog/templates/partials/header.html
{% load static %}
<!-- =======================
Header START -->
<header class="navbar-light navbar-sticky header-static">
<div class="navbar-top d-none d-lg-block small">
  <div class="container">
    <div class="d-md-flex justify-content-between align-items-center my-2">
      <!-- Top bar left -->
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link ps-0" href="about-us.html">درباره ما</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">آرشیو</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">خرید قالب</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="signin.html">ورود / ثبت نام</a>
        </li>
      </ul>
      <!-- Top bar right -->
      <div class="d-flex align-items-center">
        <!-- Font size accessibility START -->
        <div class="btn-group me-3" role="group" aria-label="font size changer">
          <input type="radio" class="btn-check" name="fntradio" id="font-sm">
          <label class="btn btn-xs btn-outline-primary mb-0" for="font-sm">A-</label>

          <input type="radio" class="btn-check" name="fntradio" id="font-default" checked>
          <label class="btn btn-xs btn-outline-primary mb-0" for="font-default">A</label>

          <input type="radio" class="btn-check" name="fntradio" id="font-lg">
          <label class="btn btn-xs btn-outline-primary mb-0" for="font-lg">A+</label>
        </div>

          <!-- Dark mode options START -->
        <div class="nav-item dropdown mx-2">
          <!-- Switch button -->
          <button class="modeswitch" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" data-bs-display="static">
            <svg class="theme-icon-active"><use href="#"></use></svg>
          </button>
          <!-- Dropdown items -->
          <ul class="dropdown-menu min-w-auto dropdown-menu-end" aria-labelledby="bd-theme">
            <li class="mb-1">
              <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light">
                <svg width="16" height="16" fill="currentColor" class="bi bi-brightness-high-fill fa-fw mode-switch me-1" viewBox="0 0 16 16">
                  <path d="M12 8a4 4 0 1 1-8 0 4 4 0 0 1 8 0zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
                  <use href="#"></use>
                </svg>روشن
              </button>
            </li>
            <li class="mb-1">
              <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-moon-stars-fill fa-fw mode-switch me-1" viewBox="0 0 16 16">
                  <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
                  <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
                  <use href="#"></use>
                </svg>تیره
              </button>
            </li>
            <li>
              <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-circle-half fa-fw mode-switch me-1" viewBox="0 0 16 16">
                  <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
                  <use href="#"></use>
                </svg>خودکار
              </button>
            </li>
          </ul>
        </div>
        <!-- Dark mode options END -->

        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link px-2 fs-5" href="#"><i class="fab fa-facebook-square"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link px-2 fs-5" href="#"><i class="fab fa-twitter-square"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link px-2 fs-5" href="#"><i class="fab fa-linkedin"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link px-2 fs-5" href="#"><i class="fab fa-youtube-square"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link ps-2 pe-0 fs-5" href="#"><i class="fab fa-vimeo"></i></a>
          </li>
        </ul>
      </div>
    </div>
    <!-- Divider -->
    <div class="border-bottom border-2 border-primary opacity-1"></div>
  </div>
</div>

<!-- Logo Nav START -->
<nav class="navbar navbar-expand-lg">
  <div class="container">
    <!-- Logo START -->
    <a class="navbar-brand" href="index.html">
      <img class="navbar-brand-item light-mode-item" src="{% static 'images/logo.svg' %}" alt="logo">			
      <img class="navbar-brand-item dark-mode-item" src="{% static 'images/logo-light.svg' %}" alt="logo">			
    </a>
    <!-- Logo END -->

    <!-- Responsive navbar toggler -->
    <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="text-body h6 d-none d-sm-inline-block">منو</span>
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Main navbar START -->
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav navbar-nav-scroll mx-auto">

        <!-- Nav item 1 Demos -->
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'blog:index' %}" id="homeMenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">خانه</a>
        </li>

        <!-- Nav item 2 Pages -->
        <li class="nav-item ">
          <a class="nav-link" href="#" id="pagesMenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">صفحات</a>
  
        </li>

        <!-- Nav item 3 Post -->
        <li class="nav-item ">
          <a class="nav-link " href="#" id="postMenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">لیست مقالات</a>

        </li>

        <!-- Nav item 4 link-->
        <a class="nav-link" href="{% url 'blog:profile' %}">پروفایل</a>
        <li class="nav-item"></li>
      </ul>
    </div>
    <!-- Main navbar END -->

    <!-- Nav right START -->
    <div class="nav flex-nowrap align-items-center">
      <!-- Nav Button -->
      <div class="nav-item d-none d-md-block">
        <a href="#" class="btn btn-sm btn-danger mb-0 mx-2">خبرنامه</a>
      </div>
      <!-- Nav Search -->
      <div class="nav-item dropdown dropdown-toggle-icon-none nav-search">
        <a class="nav-link dropdown-toggle" role="button" href="#" id="navSearch" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-search fs-4"> </i>
        </a>
        <div class="dropdown-menu dropdown-menu-end shadow rounded p-2" aria-labelledby="navSearch">
          <form class="input-group" action="{% url 'blog:post_search' %}" method="GET">
            <input class="form-control border-success" name="query" type="search" placeholder="جستجو" aria-label="Search">
            <button class="btn btn-success m-0" value="Search" type="submit">جستجو</button>
          </form>
        </div>
      </div>
      <!-- Offcanvas menu toggler -->
      <div class="nav-item">
        <a class="nav-link p-0" data-bs-toggle="offcanvas" href="#offcanvasMenu" role="button" aria-controls="offcanvasMenu">
          <i class="bi bi-text-right rtl-flip fs-2" data-bs-target="#offcanvasMenu"> </i>
        </a>
      </div>
    </div>
    <!-- Nav right END -->
  </div>
</nav>
<!-- Logo Nav END -->
</header>
<!-- =======================
Header END -->
{% comment %} <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blog:index' %}">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="d-flex" action="{% url 'blog:post_search' %}" method="GET">
          <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search">
          <input class="btn btn-outline-success" value="Search" type="submit">
        </form>
      </div>
    </div>
</nav> {% endcomment %}

blog/templates/partials/latest_post.html
<div class="container">
    <div class="row">
        <h1>اخرین پست ها</h1>
        {% for post in l_post %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">{{post.title}}</h5>
              <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
              <a href="{{post.get_absolute_url}}" class="btn btn-primary">{{post.title}}</a>
            </div>
          </div>
                        
          {% endfor %}
    </div>
</div>

blog/templates/partials/pageination.html
<nav class="my-5" aria-label="navigation">
  {% comment %} <div style="margin-left: 42%;" > {% endcomment %}
    <ul class="pagination d-inline-block d-md-flex justify-content-center">
    {% if page_obj.has_previous %}
    {% comment %} <a href="?page={{ page_obj.previous_page_number }}">قبلی</a> {% endcomment %}
    <li class="page-item">
      <a class="page-link active" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">قبلی</a>
    </li>
    {% if page_obj.number > 3 %}
    {% comment %} <a href="?page=1">1</a> {% endcomment %}
    <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
    {% if page_obj.number > 4 %}
    <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
    {% endif %}
    {% endif %}
    {% endif %}
    
    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <li class="page-item">
      <a  class="page-link" href="?page={{ num }}">{{ num }}</a>
    </li>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    <li class="page-item">
      <a  class="page-link" href="?page={{ num }}">{{ num }}</a>
    </li>
    {% endif %}
    {% endfor %}
  
    {% if page_obj.has_next %}
    {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
      <span>...</span>
      <li class="page-item">
        <a  class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
      </li>
      {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
      <li class="page-item">
        <a  class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
      </li>
    {% endif %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">بعد</a>
    </li>
    {% comment %} <a href="?page={{ page_obj.next_page_number }}">Next Page »</a> {% endcomment %}
    {% endif %}
  </ul>
  {% comment %} </div> {% endcomment %}
</nav>