blog/urls.py
from django.urls import path
from . import views
app_name = "blog"


urlpatterns = [
    path('', views.Home  , name = "index" ),
    # path('posts/', views.Post_list , name = "Post_list"),
    path('posts/', views.PostListview.as_view() , name = "Post_list"),
    path('posts/<int:id>/', views.Post_detail , name = "Post_detail"),
    path('posts/<post_id>/comment', views.post_comments , name = "post_comments"),
    # path('posts/<pk>', views.PostDitailview.as_view() , name = "Post_detail"),
    path('ticket/', views.create_ticket , name = "create_ticket"),
    # path('posts/create/', views.crete_post , name = "crete_post"),
    path('posts/create/', views.crete_blog , name = "crete_blog"),
    path('posts/search/', views.post_search , name = "post_search"),
    path('profile/', views.profile , name = "profile"),
    path('profile/delete_post/<post_id>', views.delete_post , name = "delete_post"),
    path('profile/delete_image/<post_id>', views.delete_image , name = "delete_image"),
    path('profile/edit_post/<post_id>', views.edit_post , name = "edit_post"),

 


]

sabzweblog/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static 
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

urlpatterns+=static(settings.MEDIA_URL , document_root =settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django_jalali.db import models as jmodels
from django.urls import reverse
from django_resized import ResizedImageField
from django.db.models.signals import pre_delete
from django.dispatch import receiver
import os
from datetime import datetime
from django.template.defaultfilters import slugify
# Create your models here.
class publishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status = Post.Status.PUBLISH)
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF' ,'Draft'
        PUBLISH = 'PB' , 'Publish'
        REJECTED = 'RJ' , 'Rejected'
        
    author = models.ForeignKey(User , on_delete = models.CASCADE,related_name = "user_posts" ,verbose_name = "نویسنده")
    title = models.CharField(max_length =100 ,verbose_name = "عنوان" )
    description = models.TextField(verbose_name = "توضیحات")
    slug = models.SlugField(max_length =100)
    # time 
    publish = jmodels.jDateTimeField(default=timezone.now,verbose_name = "تاریخ انتشار")
    created = jmodels.jDateTimeField(auto_now_add=True,verbose_name = "تاریخ ساخت")
    updated = jmodels.jDateTimeField(auto_now=True)
    status = models.CharField(max_length =10 , choices = Status.choices , default = Status.DRAFT,verbose_name = "وضعیت")
    reading_time = models.PositiveIntegerField(verbose_name = "تایم مطالعه")
    # objects = models.Manager()
    objects = jmodels.jManager()
    published = publishedManager()
    class Meta:
        ordering = ['-publish']
        # for search index in table 
        indexes = [
            models.Index(fields=['-publish'])
        ]
        verbose_name = "پست"
        verbose_name_plural = "پست ها"
        
        
    def __str__(self) :
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:Post_detail", kwargs={"id": self.id})

    def save(self , *args , **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args,**kwargs)

    def delete(self , *args , **kwargs):
        for img in self.images.all():
            storage , path = img.Image_file.storage , img.Image_file.path
            storage.delete(path)
        super().delete(*args,**kwargs)


class Ticket(models.Model):
    name = models.CharField(max_length =50  ,verbose_name = "نام فرستند")
    massege = models.TextField(verbose_name = "پیام")
    email = models.EmailField(verbose_name = "ایمیل")
    phone = models.CharField(max_length =11 , verbose_name = "تلفن همراه" )
    sunject = models.CharField(max_length =100  , verbose_name = "موضوع پیام")
    class Meta:
        verbose_name = "تیکت"
        verbose_name_plural = "تیکت ها"
        
        
    def __str__(self) :
        return self.name
    
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete = models.CASCADE,related_name = "comments" ,verbose_name = "پست")
    name = models.CharField(max_length =50,verbose_name = "نام")
    body = models.TextField(verbose_name = "متن کامنت")
    created = jmodels.jDateTimeField(auto_now_add=True,verbose_name = "تاریخ ساخت")
    updated = jmodels.jDateTimeField(auto_now=True ,verbose_name = "تاریخ ویرایش")
    active = models.BooleanField(default=False ,verbose_name = "وضعیت")
    class Meta:
        ordering = ['created']
        # for search index in table 
        indexes = [
            models.Index(fields=['created'])
        ]
        verbose_name = "کامنت"
        verbose_name_plural = "کامنت ها"
        
        
    def __str__(self) :
        return f"{self.name} : {self.post}"
    
    
def upload_to(instance, filename):
    # دریافت تاریخ و زمان فعلی
    now = datetime.now()
    # تعیین مسیر آپلود بر اساس سال
    upload_path = os.path.join('Post_image', str(now.year))
    # تعیین نام فایل
    _, ext = os.path.splitext(filename)
    file_name = f'{instance.pk}{ext}'
    # ترکیب مسیر آپلود و نام فایل
    return os.path.join(upload_path, file_name)
class ImagePost(models.Model):
     post = models.ForeignKey(Post,on_delete = models.CASCADE,related_name = "images" ,verbose_name = "پست")
     Image_file = ResizedImageField(upload_to=upload_to , crop=['middle', 'center'] , size=[500,500],quality=75)
     title = models.CharField(max_length =50 , null=True,blank=True , verbose_name = "عنوان")
     description = models.CharField(max_length =255,null=True,blank=True , verbose_name = "توضیحات")
     created = jmodels.jDateTimeField(auto_now_add=True)
     
     class Meta:
        ordering = ['created']
        # for search index in table 
        indexes = [
            models.Index(fields=['created'])
        ]
        verbose_name = "تصویر پست"
        verbose_name_plural = "تصویر پست ها"       
     def __str__(self) :
        return self.title if self.title else self.Image_file.name
    
    
@receiver(pre_delete, sender=ImagePost)
def delete_image_file(sender, instance, **kwargs):
    # بدست آوردن مسیر فایل
    image_path = instance.Image_file.path
    
    # حذف فایل
    if os.path.isfile(image_path):
        os.remove(image_path)

blog/forms.py
from django import forms
from .models import Comment , Post
from django.contrib.auth.models import User

class TicketForm(forms.Form):
     subject_select = (
         ("پیشنهاد" , "پیشنهاد"),
         ("انتقاد" , "انتقاد"),
         ("گزارش" , "گزارش")
     )
     name = forms.CharField(max_length =50 , required=True)
     massege = forms.CharField(widget = forms.Textarea , required=True)
     email = forms.EmailField()
     phone = forms.CharField(max_length =11   , required=True)
     sunject = forms.ChoiceField(choices=subject_select)
    
    
     def clean_phone(self):
         data = self.cleaned_data["phone"]
         if data:
              if not data.isnumeric:
                   raise forms.ValidationError("شماره تلفن اشتباه وارد شده است باید عدد باشد !")
              else:
                   return data
class CommentForm(forms.ModelForm):      
     def clean_name(self):
         name = self.cleaned_data["name"]
         if name :
              if len(name)<3:
                   raise forms.ValidationError("نام کوتاه است!")
              else:
                   return name
     class Meta:
          model = Comment
          # exclude = ['created']
          fields = ['name','body']
class PostForm(forms.Form):
    author = forms.ModelChoiceField(queryset=User.objects.all() ,required=True)
    title = forms.CharField(max_length =50 , required=True)
    description = forms.CharField(widget = forms.Textarea , required=True)
    slug = forms.SlugField(max_length =50 , required=True)
    status_choices = (
        ('DF', 'Draft'),
        ('PB', 'Publish'),
        ('RJ', 'Rejected')
     )
    status = forms.ChoiceField(choices = status_choices ,required=True)    
    reading_time = forms.IntegerField(required=True)

    def clean_title(self):
         title = self.cleaned_data["title"]
         if title:
              if len(title)<3:
                   raise forms.ValidationError("نام کوتاه است!")
              else:
                    return title
               
class CratePost(forms.ModelForm):
     image1 = forms.ImageField(label='تصویر اول')
     image2 = forms.ImageField(label='تصویر دوم')
     class Meta:
          model = Post
          fields = ['title','description','reading_time',]
class SearchForm(forms.Form):
     query = forms.CharField()

blog/views.py
from django.shortcuts import render , get_object_or_404 ,redirect
from django.http import HttpResponse , Http404 
from .models import Post , Ticket , ImagePost
from .forms import *
from django.views.decorators.http import require_POST , require_GET
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic import ListView , DetailView
from django.db.models import Q
from django.contrib.postgres.search import SearchVector , SearchQuery , SearchRank ,TrigramSimilarity
from itertools import chain
# Create your views here.
def Home(request):
    return render(request , "blog/index.html" )

class PostListview(ListView):
    paginate_by = 3  
    queryset = Post.published.all()
    context_object_name = "posts"
    template_name = "blog/list.html"

def Post_detail(request , id):
    post =  get_object_or_404(Post , id=id , status = Post.Status.PUBLISH)
    # try:
    #     post = Post.published.get(id=id)
    # except:
    #     raise Http404("not found post!...")
    form = CommentForm()
    comment = post.comments.filter(active =True)
    context = {
        "post" : post,
        "form" : form,
        "commetn":comment,
    }
    return render (request , "blog/detail.html" , context)
    
def create_ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(
                name = cd["name"],
                massege = cd["massege"],
                email = cd["email"],
                phone = cd["phone"],
                sunject = cd["sunject"],
                )
            return redirect("blog:index")
            
    else:
        form = TicketForm()
        # context = {
        #     "form" : form
        # }
    return render(request, "forms/ticket.html", {"form" : form})    

@require_POST
def post_comments(request , post_id):
    post = get_object_or_404(Post , id=post_id , status = Post.Status.PUBLISH) 
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        "post": post,
        "form" : form,
        "comment":comment
    }
    return render(request , "forms/comment.html" ,context) 

def crete_blog(request):
    if request.method == "POST":
        form = CratePost(request.POST , request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            img1 = ImagePost.objects.create(Image_file=form.cleaned_data['image1'] , post=post)
            post.images.add(img1)
            img2 = ImagePost.objects.create(Image_file=form.cleaned_data['image2'] , post=post)
            post.images.add(img2)
            post.save()
            return redirect("blog:index")
    else:
        form = CratePost()
    return render (request , "blog/createpost.html" , {"form" :form,})

@require_GET
def post_search(request):
    query=None
    result=[]
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # ============
            post_results = Post.objects.filter(
                Q(title__icontains=query) | Q(description__icontains=query)
            )
            image_post_results = ImagePost.objects.filter(
                Q(title__icontains=query) | Q(description__icontains=query)
            )

            result = list(chain(post_results, image_post_results))
            # ==========
            # result = Post.objects.filter(description__search = query)
            # ===================
            # search_query = SearchQuery(query)
            # search_vector = SearchVector('title' , 'description')
            # result = Post.objects.annotate(search=search_vector , rank=SearchRank(search_vector,search_query)).filter(search  = search_query).order_by('-rank')
            #  SearchQuery(query) فارسی کامل پشتیبانی نمیشود
            # ====================
            # post_results = Post.objects.annotate(similarity=TrigramSimilarity('title', query) + TrigramSimilarity('description', query)).filter(similarity__gt=0.1).order_by('-similarity')
            # image_post_results = ImagePost.objects.annotate(similarity=TrigramSimilarity('title', query) + TrigramSimilarity('description', query)).filter(similarity__gt=0.1).order_by('-similarity')
            # result = list(chain(post_results, image_post_results))
    context = {
        'query':query,
        'result':result,
    }
    return render(request , 'blog/index.html' , context)

def profile(request):
    user = request.user
    post = Post.published.filter(author=user)
    # print(post)
    context = {
        'post':post,
    }
    return render(request , 'blog/profile.html' , context)


def delete_post(request, post_id):
    post = get_object_or_404(Post,id=post_id)
    if request.method == "POST":
        post.delete()
        return redirect("blog:profile")
    return render(request, 'forms/delete-post.html' , {post:'post'})

def delete_image(request, post_id):
    image = get_object_or_404(ImagePost,id=post_id)
    image.delete()
    return redirect("blog:profile")
    return render(request, 'forms/delete-image.html' , {image:'image'})
    
def edit_post(request, post_id):
    post = get_object_or_404(Post,id=post_id)
    if request.method == "POST":
            form = CratePost(request.POST , request.FILES , instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.save()
                img1 = ImagePost.objects.create(Image_file=form.cleaned_data['image1'] , post=post)
                post.images.add(img1)
                img2 = ImagePost.objects.create(Image_file=form.cleaned_data['image2'] , post=post)
                post.images.add(img2)
                post.save()
                return redirect("blog:index")
    else:
        form = CratePost( instance=post)
        return render (request , "blog/createpost.html" , {"form" :form, "post" :post})

blog/templates/blog/createpost.html
{% extends "parent/base.html" %}
{% block title %}ایجاد پست {% endblock title %}

{% block content %}

<h1>create post</h1>
{% comment %} {% if form.errors %}
    <div class="alert alert-danger">
        <ul>
            {% for field, errors in form.errors.items %}
                {% for error in errors %}
                    <li>{{ field }}: {{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
{% endif %} {% endcomment %}
<div class="container">
    <form method = "POST" enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.as_p}} 
        {% for img in post.images.all %}
            <img with="300px" height="200px" src="{{img.Image_file.url}}" alt="{{img.title}}"> 
            <a href="{% url 'blog:delete_image' img.id %}">حذف پست</a>
        {% endfor %}   
        <input type="submit" value="ثبت نظر" class="btn btn-primary float-end">
        
    </form>
    
</div>

<br><br><br><br>
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="signup-form">
                <form action="" class="mt-5 border p-4 bg-light shadow">
                    <h4 class="mb-5 text-secondary">create post</h4>
                    <div class="row">
                        <div class="mb-3 col-md-6">
                            <label>عنوان پست<span class="text-danger">*</span></label>
                            <input type="text" name="title" {% if form.title.value %} value="{{form.title.value}}" {% endif %}  class="form-control" >
                            {% if form.title.errors %}
                                <p class="alert alert-danger">
                                    {% for error in form.title.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </p>
                        {% endif %}

                        </div>
                        <div class="mb-3 col-md-6">
                            <label>نویسنده<span class="text-danger">*</span></label>
                            <select name="author" class="form-control" >
                                <option value="">نویسنده را انتخاب کنید</option>
                                {% for U in form.author.field.queryset %}
                                <option value="{{U.id}}">{{U.username}}</option>
                                {% endfor %}
                            </select>
                            {% if form.author.errors %}
                                <p class="alert alert-danger">
                                    {% for error in form.author.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </p>
                        {% endif %}

                        </div>

                        <div class="mb-3 col-md-6">
                            <label>اسلاگ<span class="text-danger">*</span></label>
                            <input type="text" name="slug" class="form-control">
                            {% if form.slug.errors %}
                            <p class="alert alert-danger">
                                {% for error in form.slug.errors %}
                                    {{ error }}
                                {% endfor %}
                            </p>
                            {% endif %}

                        </div>
                        <div class="mb-3 col-md-6">
                            <label>وضعیت<span class="text-danger">*</span></label>
                            <select name="status" class="form-control">
                                <option value="">وضعیت</option>
                               {% for value, label in form.fields.status.choices %}
                               <option value="{{ value }}">{{ label }}</option>
                               {% endfor %}                                   
                            </select>
                            {% if form.status.errors %}
                            <p class="alert alert-danger">
                                {% for error in form.status.errors %}
                                    {{ error }}
                                {% endfor %}
                            </p>
                              {% endif %}

                        </div>
                        
                        <div class="mb-3 col-md-12">
                            <label>تایم مطالعه <span class="text-danger">*</span></label>
                            <input type="number" name="reading_time" class="form-control">
                            {% if form.reading_time.errors %}
                            <p class="alert alert-danger">
                                {% for error in form.reading_time.errors %}
                                    {{ error }}
                                {% endfor %}
                            </p>
                    {% endif %}

                        </div>
                        <div class="mb-3 col-md-12">
                            <label>توضیحات<span class="text-danger">*</span></label>
                            <textarea  cols="30" rows="10" name="description" class="form-control"></textarea>
                            {% if form.description.errors %}
                            <p class="alert alert-danger">
                                {% for error in form.description.errors %}
                                    {{ error }}
                                {% endfor %}
                            </p>
                    {% endif %}

                        </div>
                        <div class="col-md-12">
                            <input type="submit" value="ثبت نظر" class="btn btn-primary float-end">
                           {% comment %} <button >Signup Now</button> {% endcomment %}
                        </div>
                    </div>
                </form>
                <p class="text-center mt-3 text-secondary">If you have account, Please <a href="#">Login Now</a></p>
                {% comment %} <form action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                </form> {% endcomment %}
            </div>
        </div>
    </div>
</div>
{% endblock  %}

blog/templates/blog/detail.html
{% extends "parent/base.html" %}
{% load jformat %}
{% block title %}detail post{% endblock title %}

{% block content %}
{% comment %} <h1>hello worls</h1> {% endcomment %}
<hr>
<h1>{{post}}</h1>
<p>{{post.publish|jformat:"%Y/%m/%d - (%H:%M)"}}</p>

<div>
    {% for img in post.images.all %}
        <img with="300px" height="200px" src="{{img.Image_file.url}}" alt="{{img.title}}">    
    
    {% endfor %}
</div>

<hr>
<form method="POST" action="{% url "blog:post_comments" post.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value = "ارسال کامنت" >
</form>

<hr><hr><br>
<div>
{% with commetn.count as cm %}
{% comment %} pluralize  for s jame gozashteh mishe {% endcomment %}
    {{ cm }} commetn{{ cm|pluralize }}
{% endwith %}
</div>

{% for i in commetn %}
    <h1> {{i.name}} </h1>
    <br>
    <p> {{i.body|linebreaks}} </p>
{% empty %}
    <h3>کامنتی وجود ندارد</h3>
{% endfor %}


{% endblock content %}

blog/templates/blog/profile.html
{% extends "parent/base.html" %}
{% block title %}list post{% endblock title %}

{% block content %}

<a href="{% url 'blog:crete_blog' %}">ایجاد پست جدید</a>


<div class="container mt-5" dir="rtl">
    <table class="table table-hover mt-5">
        <thead>
          <tr>
              <th scope="col">ردیف</th>
              <th scope="col">عنوان</th>
              <th scope="col">ویرایش</th>
              <th scope="col">حذف</th>
          </tr>
        </thead>
        <tbody>
            {% for item in post %}
          <tr>
                <th  >{{forloop.counter}}</th>
                <td><a style="text-decoration: none;" href="{{item.get_absolute_url}}">{{item.title}}</a></td>
                <td><a href="{% url 'blog:edit_post' item.id %}" class="btn btn-primary" >ویرایش</a></td>
                <td><a href="{% url 'blog:delete_post' item.id %}" class="btn btn-danger">حدف</a></td>

            </tr>
            {% endfor %}
        </tbody>
        
      </table>
</div>

{% endblock content %}

blog/templates/blog/search.html
{% extends "parent/base.html" %}
{% load blog_tags %}
{% block title %}search post{% endblock title %}

{% block content %}
 {% if query %}
    {{result.count}}
{% endif %} 


{% for post in result %}
<a href="{{post.get_absolute_url}}">{{post.title}}</a>
{% empty %}
    {% comment %} چیزی یافت نشد {% endcomment %}
{% endfor %}
{% endblock content %}